### ISSUE TITLE
execute any get command force close terminal on window

### ISSUE THREAD

**Issue by daveMcelf** [jonataslaw/get_cli#27]
After installing get_cli from pub with `pub global activate get_cli`, type in any get command in the terminal, it just force close the terminal after execute the command.

get_cli: 1.3.12
OS: Window 10

**Comment by daveMcelf** [comment]
if anyone face the same problem, installing Windows powershell and run the command from it instead of using command prompt fix the issue for me.

**Comment by Anthrapper** [comment]
Please find a better solution, cant always use powershell. Most of the users use cmd , and they will get stuck in this problem

**Comment by viplike** [comment]
found decision, which is working for windows..

replace the content in this file: 
C:\Users\<Your current user>\AppData\Roaming\Pub\Cache\bin\get.bat

to:
`
@echo off
pub global run get_cli:get %*
`

that's all. we off the checking of the get snaphot version. it can be a little crutchy, but it's on your choice to use it or not before repository team will fix this issue.

**Comment by CpdnCristiano** [comment]
I will check this error, it did not happen to me

**Comment by lucasbaggio** [comment]
i also had the same problem, I can write any other command that is not related to Get and works normally, but when I use any Get command, it executes the code and closes immediately.

I couldn't use your solution @viplike 
When i try to open the file, the CMD opens and closes immediately, with the following information: 
![image](https://user-images.githubusercontent.com/54324200/104062845-f4b22200-51d9-11eb-8dce-8b8dc4f6d4db.png)

get_cli 1.4.1
OS: Windows 10 Home

**Comment by lucasbaggio** [comment]
After some hours, i found one solution, maybe the cause of the problem.

As of version 1.21 of Flutter, the installation already includes the DART SDK. So, I had two versions of DART on my machine. The problem was in the older version set in the environment variable.

The solution was to change the path in the variable.

It was C: \ src \ flutter \ bin
I switched to **C: \ src \ flutter \ bin \ cache \ dart-sdk \ bin**

As the image below:
![image](https://user-images.githubusercontent.com/54324200/104068423-a275fe80-51e3-11eb-9949-500572a9b18c.png)

So it worked
